import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getEnvVar } from './env.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const webEnv = path.join(ROOT, '..', 'web', '.env.local');
const agentEnv = path.join(ROOT, '..', 'agent', '.env.local');
const SUPABASE_URL = getEnvVar('NEXT_PUBLIC_SUPABASE_URL', webEnv);
const SUPABASE_SERVICE_KEY = getEnvVar('SUPABASE_SERVICE_ROLE_KEY', webEnv);
const GROQ_API_KEY = getEnvVar('GROQ_API_KEY', agentEnv);

export async function fetchLesson(slug) {
  const res = await fetch(
    `${SUPABASE_URL}/rest/v1/curriculum_nodes?select=id,title,slug,markdown_content&slug=eq.${slug}`,
    { headers: { apikey: SUPABASE_SERVICE_KEY, Authorization: `Bearer ${SUPABASE_SERVICE_KEY}` } },
  );
  const rows = await res.json();
  if (!res.ok || !Array.isArray(rows)) throw new Error(`Lesson fetch failed: ${JSON.stringify(rows)}`);
  if (rows.length === 0) throw new Error(`No lesson found with slug "${slug}"`);
  return rows[0];
}

// Real code, extracted verbatim from the lesson's own markdown — never
// regenerated by the LLM. This is the whole safety story for a programming
// course: the model is only ever allowed to narrate code that already
// exists in the reviewed lesson content, never write its own.
function extractCodeBlocks(markdown) {
  const blocks = [];
  const re = /```(?:python|python-run)\n([\s\S]*?)```/g;
  let match;
  while ((match = re.exec(markdown)) !== null) {
    blocks.push(match[1].replace(/\n$/, ''));
  }
  return blocks;
}

function stripForPrompt(markdown) {
  let i = 0;
  return markdown.replace(/```(?:python|python-run)\n[\s\S]*?```/g, () => `[CODE_BLOCK_${i++}]`);
}

async function callGroq(title, strippedMarkdown, codeBlockCount) {
  const prompt = `You are writing the spoken narration script for a full-length teaching video (target: about 5 minutes of narration, roughly 700-800 spoken words total), based on an existing, already-reviewed lesson from a real Python course. Lesson title: "${title}".

Below is the lesson's content with its code examples replaced by placeholders like [CODE_BLOCK_0], [CODE_BLOCK_1], etc. (${codeBlockCount} code block(s) total, numbered in order of appearance).

Your job: break this lesson into a thorough sequence of video scenes (aim for 12-20 scenes — this is a full lesson video, not a short trailer) that a narrator will read aloud over animated visuals. Cover the lesson comprehensively: every major heading/section in the source content should map to at least one scene, not just the highlights. Two scene types only:
- "Concept": explains one idea in plain spoken language (no code visible). Needs "heading" (a short phrase, under 8 words), "body" (one short supporting sentence, optional), and "narration" (what the narrator says out loud — natural spoken English, 3-6 sentences, NOT read verbatim from the markdown — elaborate and explain the "why," don't just restate the "what").
- "Code": shows one existing code example while the narrator explains it. Needs "codeRef" (the integer index of the [CODE_BLOCK_N] it corresponds to — must reference a real block that exists), "heading" (a short caption, under 8 words), and "narration" (explaining what the code does, why it's written that way, and what the reader should notice, 3-6 sentences).

Rules:
- Every codeRef must be a real block index between 0 and ${codeBlockCount - 1}.
- Cover every code block in the lesson (use multiple Concept scenes around a single code block if it needs building up before AND explaining after).
- Narration must only describe what's actually in the lesson — do not invent facts, numbers, or claims not present below.
- Do not include a title/intro scene or a closing scene — those are added separately.
- Respond with ONLY valid JSON, no markdown fences, no commentary: {"scenes": [...]}

Lesson content:
${strippedMarkdown}`;

  const res = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: { Authorization: `Bearer ${GROQ_API_KEY}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: 'openai/gpt-oss-20b',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.4,
      response_format: { type: 'json_object' },
    }),
  });
  if (!res.ok) throw new Error(`Groq request failed (${res.status}): ${await res.text()}`);
  const data = await res.json();
  const content = data.choices?.[0]?.message?.content;
  if (!content) throw new Error(`No content in Groq response: ${JSON.stringify(data)}`);
  return JSON.parse(content);
}

export async function generateScenesForLesson(slug) {
  const lesson = await fetchLesson(slug);
  const codeBlocks = extractCodeBlocks(lesson.markdown_content);
  const stripped = stripForPrompt(lesson.markdown_content);

  console.log(`"${lesson.title}": ${codeBlocks.length} real code block(s) found`);
  const groqResponse = await callGroq(lesson.title, stripped, codeBlocks.length);
  const bodyScenes = groqResponse.scenes ?? groqResponse.body_scenes ?? groqResponse;
  if (!Array.isArray(bodyScenes)) {
    throw new Error(`Groq response has no scenes array: ${JSON.stringify(groqResponse).slice(0, 500)}`);
  }

  const scenes = [
    { id: `${slug}-title`, type: 'LessonTitle', heading: lesson.title, subheading: 'Jua Institute', narration: `${lesson.title}.` },
  ];

  bodyScenes.forEach((s, i) => {
    // Groq's JSON-object mode doesn't always keep the exact key name for
    // "type" — fall back to inferring it from shape rather than failing the
    // whole lesson over a naming quirk in one field.
    if (!s.type) {
      s.type = typeof s.codeRef === 'number' || s.code_ref !== undefined ? 'Code' : 'Concept';
      s.codeRef = s.codeRef ?? s.code_ref;
    }
    if (s.type === 'Code') {
      if (typeof s.codeRef !== 'number' || s.codeRef < 0 || s.codeRef >= codeBlocks.length) {
        throw new Error(`Scene ${i} has an invalid codeRef: ${s.codeRef} (${codeBlocks.length} block(s) available)`);
      }
      scenes.push({
        id: `${slug}-code-${i}`,
        type: 'Code',
        heading: s.heading,
        code: codeBlocks[s.codeRef],
        narration: s.narration,
      });
    } else if (s.type === 'Concept') {
      scenes.push({
        id: `${slug}-concept-${i}`,
        type: 'Concept',
        heading: s.heading,
        body: s.body ?? '',
        narration: s.narration,
      });
    } else {
      throw new Error(`Unknown scene type from Groq: ${s.type}`);
    }
  });

  scenes.push({
    id: `${slug}-closing`,
    type: 'LessonClosing',
    heading: 'Nice work.',
    narration: `That covers ${lesson.title}. Head into the practice below to try it yourself.`,
  });

  return { lesson, scenes };
}

// CLI usage: node scripts/generate-script.mjs <slug>
// (compares basenames rather than full file:// URLs — on Windows the two
// forms don't string-match even when they point at the same file)
if (process.argv[1] && path.basename(process.argv[1]) === 'generate-script.mjs') {
  const slug = process.argv[2];
  if (!slug) {
    console.error('Usage: node scripts/generate-script.mjs <lesson-slug>');
    process.exit(1);
  }
  const { scenes } = await generateScenesForLesson(slug);
  fs.writeFileSync(path.join(ROOT, 'scenes.json'), JSON.stringify(scenes, null, 2));
  console.log(`Wrote ${scenes.length} scenes to scenes.json`);
}
